os: linux
dist: bionic

git:
  depth: false

addons:
  hosts:
    - magento2.docker
    - magento2.test

services:
  - docker

language: php

stages:
  - static-unit
  - integration
  - build-images
  - test

jobs:
  include:
    - stage: static-unit
      php: '7.1'
      script: ./tests/travis/static-unit.sh;
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.2'
      env:
        - TEST_SUITE=static-unit
    - script: ./tests/travis/static-unit.sh;
      php: '7.3'
      env:
        - TEST_SUITE=static-unit
    - stage: integration
      script: ./vendor/bin/phpunit --configuration ./tests/integration;
      php: '7.1'
      env:
        - TEST_SUITE=integration
    - script: ./vendor/bin/phpunit --configuration ./tests/integration;
      php: '7.2'
      env:
        - TEST_SUITE=integration
    - script: ./vendor/bin/phpunit --configuration ./tests/integration;
      php: '7.3'
      env:
        - TEST_SUITE=integration
    - stage: build-images
      env:
        - TEST_SUITE=build-images
      script:
        - if [ $TRAVIS_SECURE_ENV_VARS == "true" ] then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi;
        - if [ $TRAVIS_SECURE_ENV_VARS == "true" ] then ./tests/travis/images.sh; fi;
    - stage: test
      php: '7.1'
      dist: xenial
      env:
        - TEST_SUITE=functional
    - php: '7.2'
      dist: xenial
      env:
        - TEST_SUITE=functional
    - php: '7.3'
      env:
        - TEST_SUITE=functional

install: composer update

before_script:
  - sudo sysctl -w vm.max_map_count=262144

script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [ $TEST_SUITE == "functional" ]; then ./tests/travis/functional.sh; fi;
